Changeable lift speeds
fookatchu/SL1toPhoton pull request #7
Opened 2020-04-02 16:17 UTC by csakip

Switched to pyphotonfile 0.2.1
Lift speeds can be changed.
Exposure time can be float.

I don't have Qt Creator so ui_mainwindow.py was edited directly.

2020-04-03 09:35 UTC, fookatchu commented
Thanks for the work! I am currently quite busy with other projects, but I plan to do a new release sometime down the road once I fixed some issues with pyphotonfile. Until then I won't be able to merge the pull request. I will most likely pick some of your stuff and do a refactor so that there are not two 'SL1Reader' classes, so don't ne discouraged if I don't merge the whole pull request.

2020-09-02 03:36 UTC, cab404 commented
@csakip Hello! Can you please PR this to https://github.com/cab404/SL1ToPhoton as well? I will maintain a fork until @fookatchu finds time to do so here)

2020-09-14 09:54 UTC, cab404 commented
This PR is unfocused, and merging it actually breaks output files. Please, review your changes, @csakip

2020-09-14 10:11 UTC, cab404 requested changes

2020-09-14 10:11 UTC, cab404 commented on SL1_to_Photon.py
> +    photon.print_time = int(float(sl1.config['printTime']))
All of those settings do not fit this PR, and require explanation.

2020-09-14 10:11 UTC, cab404 commented on SL1_to_Photon_gui.py
> +        photon.version = 2;
As well as those

2020-09-14 11:01 UTC, cab404 commented on SL1_to_Photon.py
> +    photon.print_time = int(float(sl1.config['printTime']))
Ooof, sorry, didn't update pyphotonfile prior to review — everything is clearer now)

2020-09-15 05:21 UTC, cab404 commented on SL1_to_Photon.py
> +    photon.print_time = int(float(sl1.config['printTime']))
Merged that into my fork

2024-01-20 20:28 UTC, closed without merging